name: Conftest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conftest:
    name: Policy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Conftest Image
        run: docker pull openpolicyagent/conftest:latest

      - name: Run Conftest
        run: |
          docker run --rm -v $(pwd):/project -w /project openpolicyagent/conftest:latest test --policy policy .
