name: Conftest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Run Conftest
        uses: sentenz/actions/conftest@latest
        with:
          path: "."
          output-format: "github"
          fail-on-warn: "false"
          all-namespaces: "true"
