name: Regal

on:
  pull_request:

jobs:
  lint-rego:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Run Regal
        uses: sentenz/actions/regal@main
        with:
          path: "./tests/policy"
          output-format: "github"
          regal-version: "latest"
